/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <stdlib.h>
#include <stdbool.h>
#include <assert.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_createTaskList_shouldCreateNewTaskList();
extern void test_freeTaskList_shouldFreeAndNullTaskList();
extern void test_createTaskList_shouldCreateNullListEnds();
extern void test_createTask_shouldCreateNewTaks();
extern void test_freeTask_shouldFreeAndNullTask();
extern void test_appendTask_shouldMakeTheTaskFirstAndLastOnEmptyList();
extern void test_appendTask_shouldUpdateLastTaskWhenListNotEmpty();
extern void test_execTaskList_shouldExecuteAllTasksInOrder();
extern void test_execTaskList_shouldReturnTrueIfAllTasksSucceed();
extern void test_execTaskList_shouldReturnFalseIfAnyTasksFails();
extern void test_execTaskList_shouldExecAllUndoFunctionsFromFiledToFirst();


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("../../../tests/unit/TaskList.test.c");
  run_test(test_createTaskList_shouldCreateNewTaskList, "test_createTaskList_shouldCreateNewTaskList", 140);
  run_test(test_freeTaskList_shouldFreeAndNullTaskList, "test_freeTaskList_shouldFreeAndNullTaskList", 148);
  run_test(test_createTaskList_shouldCreateNullListEnds, "test_createTaskList_shouldCreateNullListEnds", 155);
  run_test(test_createTask_shouldCreateNewTaks, "test_createTask_shouldCreateNewTaks", 164);
  run_test(test_freeTask_shouldFreeAndNullTask, "test_freeTask_shouldFreeAndNullTask", 172);
  run_test(test_appendTask_shouldMakeTheTaskFirstAndLastOnEmptyList, "test_appendTask_shouldMakeTheTaskFirstAndLastOnEmptyList", 179);
  run_test(test_appendTask_shouldUpdateLastTaskWhenListNotEmpty, "test_appendTask_shouldUpdateLastTaskWhenListNotEmpty", 192);
  run_test(test_execTaskList_shouldExecuteAllTasksInOrder, "test_execTaskList_shouldExecuteAllTasksInOrder", 207);
  run_test(test_execTaskList_shouldReturnTrueIfAllTasksSucceed, "test_execTaskList_shouldReturnTrueIfAllTasksSucceed", 225);
  run_test(test_execTaskList_shouldReturnFalseIfAnyTasksFails, "test_execTaskList_shouldReturnFalseIfAnyTasksFails", 238);
  run_test(test_execTaskList_shouldExecAllUndoFunctionsFromFiledToFirst, "test_execTaskList_shouldExecAllUndoFunctionsFromFiledToFirst", 254);

  return UnityEnd();
}
