#!/bin/bash

[ -d /etc/overboot.d ] || mkdir /etc/overboot.d
[ -f /etc/overboot.yaml ] || cp /usr/share/overboot/overboot.yaml.default /etc/overboot.yaml

chmod +x /usr/share/initramfs-tools/scripts/local-bottom/obinit

update-initramfs -u
