kind: pipeline
name: default

steps:
- name: build-obinit
  image: chodak166/dev-cpp:focal-base-1.1
  commands:
  - git submodule init
  - git submodule update
  - cd obinit
  - mkdir build
  - cd build
  - cmake
    -D CMAKE_BUILD_TYPE=Release
    ..
  - cmake --build .

- name: test-obinit
  image: chodak166/dev-cpp:focal-base-1.0
  privileged: true
  commands:
  - cd obinit/build
  - ctest -V .
