#!/bin/sh

PREREQ="udev"

prereqs()
{
    echo "${PREREQ}"
}

case ${1} in
    prereqs)
        prereqs
        exit 0
        ;;
esac

readWithTimeout() {
        timeout_s=$1
        old=$(stty -g)
        stty raw -echo min 0 time $(($timeout_s * 10))
        printf '%s' $(dd bs=1 count=1 2>/dev/null)
        stty $old
}

obBin=${rootmnt}/sbin/obinit
timeout=5

if [ ! -f ${obBin} ]; then
  echo "${obBin} not found. Boot will continue after ${timeout} seconds. Press enter to continue without timeout."
  readWithTimeout ${timeout}
  exit 0
fi

${obBin} -c ${rootmnt}/etc/overboot.yaml

exit 0
