/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "ob/ObDefs.h"
#include <stdbool.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_obInitializeOverboot_shouldMountDataDevice();
extern void test_obInitializeOverboot_shouldPrepareOverlayDirectory();
extern void test_obInitializeOverboot_shouldUseTmpfsIfConfigured();
extern void test_obInitializeOverboot_shouldSetTmpfsSize();
extern void test_obInitializeOverboot_shouldClearUpperIfConfigured();
extern void test_obInitializeOverboot_shouldMoveRootfs();
extern void test_obInitializeOverboot_shouldBindUpperLayerIfConfigured();
extern void test_obInitializeOverboot_shouldMountOverlayFs();
extern void test_obInitializeOverboot_shouldMountAllLayersRequiredByHeadLayer();
extern void test_obInitializeOverboot_shouldBindOverlayDirectory();
extern void test_obInitializeOverboot_shouldBindRepositoryIfConfigured();
extern void test_obInitializeOverboot_shouldBindDurables();
extern void test_obInitializeOverboot_shouldInitializeDurablesIfConfigured();
extern void test_obInitializeOverboot_shouldNotInitializeDurablesIfConfigured();
extern void test_obInitializeOverboot_shouldUpdateFstab();
extern void test_obDeinitializeOverboot_shouldRestoreRootfs();


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("../../../tests/integration/ObInit.test.c");
  run_test(test_obInitializeOverboot_shouldMountDataDevice, "test_obInitializeOverboot_shouldMountDataDevice", 23);
  run_test(test_obInitializeOverboot_shouldPrepareOverlayDirectory, "test_obInitializeOverboot_shouldPrepareOverlayDirectory", 28);
  run_test(test_obInitializeOverboot_shouldUseTmpfsIfConfigured, "test_obInitializeOverboot_shouldUseTmpfsIfConfigured", 33);
  run_test(test_obInitializeOverboot_shouldSetTmpfsSize, "test_obInitializeOverboot_shouldSetTmpfsSize", 38);
  run_test(test_obInitializeOverboot_shouldClearUpperIfConfigured, "test_obInitializeOverboot_shouldClearUpperIfConfigured", 43);
  run_test(test_obInitializeOverboot_shouldMoveRootfs, "test_obInitializeOverboot_shouldMoveRootfs", 48);
  run_test(test_obInitializeOverboot_shouldBindUpperLayerIfConfigured, "test_obInitializeOverboot_shouldBindUpperLayerIfConfigured", 53);
  run_test(test_obInitializeOverboot_shouldMountOverlayFs, "test_obInitializeOverboot_shouldMountOverlayFs", 58);
  run_test(test_obInitializeOverboot_shouldMountAllLayersRequiredByHeadLayer, "test_obInitializeOverboot_shouldMountAllLayersRequiredByHeadLayer", 63);
  run_test(test_obInitializeOverboot_shouldBindOverlayDirectory, "test_obInitializeOverboot_shouldBindOverlayDirectory", 68);
  run_test(test_obInitializeOverboot_shouldBindRepositoryIfConfigured, "test_obInitializeOverboot_shouldBindRepositoryIfConfigured", 73);
  run_test(test_obInitializeOverboot_shouldBindDurables, "test_obInitializeOverboot_shouldBindDurables", 78);
  run_test(test_obInitializeOverboot_shouldInitializeDurablesIfConfigured, "test_obInitializeOverboot_shouldInitializeDurablesIfConfigured", 83);
  run_test(test_obInitializeOverboot_shouldNotInitializeDurablesIfConfigured, "test_obInitializeOverboot_shouldNotInitializeDurablesIfConfigured", 88);
  run_test(test_obInitializeOverboot_shouldUpdateFstab, "test_obInitializeOverboot_shouldUpdateFstab", 93);
  run_test(test_obDeinitializeOverboot_shouldRestoreRootfs, "test_obDeinitializeOverboot_shouldRestoreRootfs", 98);

  return UnityEnd();
}
